import express from "express";
import cors from "cors";
import db from "./db.js";

import ownerRoutes from "./routes_owner/index.js";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// ===== HEALTH =====
app.get("/health", (req, res) => res.json({ ok: true }));

// ===== OWNER API =====
app.use("/owner", ownerRoutes);

// ===== ENSURE SALONS TABLE =====
async function ensureSalonsTable() {
  if (db.mode === "POSTGRES") {
    await db.run(`
      CREATE TABLE IF NOT EXISTS salons (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        slug TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
        updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
      );
    `);
  } else {
    await db.run(`
      CREATE TABLE IF NOT EXISTS salons (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        slug TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'active',
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      );
    `);
  }
}

// ===== SALON CONTEXT RESOLVER (AUTO-CREATE) =====
app.use("/s/:slug", async (req, res, next) => {
  try {
    const slug = req.params.slug;

    const selectSql =
      db.mode === "POSTGRES"
        ? "SELECT id, slug, status FROM salons WHERE slug = $1"
        : "SELECT id, slug, status FROM salons WHERE slug = ?";

    let salon = await db.get(selectSql, [slug]);

    // AUTO-CREATE IF NOT EXISTS
    if (!salon) {
      const insertSql =
        db.mode === "POSTGRES"
          ? `
            INSERT INTO salons (slug, name, status)
            VALUES ($1, $2, 'active')
            ON CONFLICT (slug) DO NOTHING
            RETURNING id, slug, status;
          `
          : `
            INSERT OR IGNORE INTO salons (slug, name, status)
            VALUES (?, ?, 'active');
          `;

      if (db.mode === "POSTGRES") {
        const row = await db.get(insertSql, [slug, slug]);
        salon = row;
      } else {
        await db.run(insertSql, [slug, slug]);
        salon = await db.get(selectSql, [slug]);
      }
    }

    if (!salon) return res.status(500).json({ error: "SALON_CREATE_FAILED" });
    if (salon.status !== "active")
      return res.status(403).json({ error: "SALON_INACTIVE" });

    req.salon = salon;
    req.salon_id = salon.id;
    next();
  } catch (e) {
    console.error("[SALON RESOLVER]", e);
    res.status(500).json({ error: "SALON_RESOLVE_FAILED" });
  }
});

// ===== RESOLVE API =====
app.get("/s/:slug/resolve", (req, res) => {
  res.json({
    ok: true,
    salon_id: String(req.salon_id),
    slug: req.salon.slug,
  });
});

// ===== START =====
ensureSalonsTable().then(() => {
  app.listen(PORT, () => {
    console.log(`TOTEM API running on port ${PORT}`);
  });
});
