import express from "express";
import cors from "cors";
import db from "./db.js";

const app = express();
const PORT = process.env.PORT || 3000;

app.use(cors());
app.use(express.json());

// ===== HEALTH =====
app.get("/health", (req, res) => res.json({ ok: true }));

// ===== BOOTSTRAP (FIX LEGACY PROD SCHEMA) =====
async function bootstrap() {
  try {
    if (db.mode === "POSTGRES") {
      // ensure table exists (no-op if exists)
      await db.run(`
        CREATE TABLE IF NOT EXISTS salons (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          slug TEXT NOT NULL UNIQUE,
          name TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
      `);

      // add missing column 'status' safely
      await db.run(`
        DO $$
        BEGIN
          IF NOT EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_name='salons' AND column_name='status'
          ) THEN
            ALTER TABLE salons ADD COLUMN status TEXT NOT NULL DEFAULT 'active';
          END IF;
        END $$;
      `);

      // seed if empty
      const r = await db.get(`SELECT COUNT(*)::int AS cnt FROM salons`);
      if ((r?.cnt ?? 0) === 0) {
        await db.run(`
          INSERT INTO salons (id, slug, name, status) VALUES
            (1,'salon-1','Salon 1','active'),
            (2,'salon-2','Salon 2','active'),
            (3,'salon-3','Salon 3','active'),
            (4,'salon-4','Salon 4','active'),
            (5,'salon-5','Salon 5','active')
          ON CONFLICT (id) DO NOTHING;
        `);
      }
    } else {
      // SQLITE
      await db.run(`
        CREATE TABLE IF NOT EXISTS salons (
          id INTEGER PRIMARY KEY AUTOINCREMENT,
          slug TEXT NOT NULL UNIQUE,
          name TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'active',
          created_at TEXT NOT NULL DEFAULT (datetime('now')),
          updated_at TEXT NOT NULL DEFAULT (datetime('now'))
        );
      `);
      await db.run(`
        INSERT OR IGNORE INTO salons (id, slug, name, status) VALUES
          (1,'salon-1','Salon 1','active'),
          (2,'salon-2','Salon 2','active'),
          (3,'salon-3','Salon 3','active'),
          (4,'salon-4','Salon 4','active'),
          (5,'salon-5','Salon 5','active');
      `);
    }

    console.log("[BOOTSTRAP] OK");
  } catch (e) {
    console.error("[BOOTSTRAP ERROR]", e);
    process.exit(1);
  }
}

// ===== SALON CONTEXT RESOLVER =====
app.use("/s/:slug", async (req, res, next) => {
  try {
    const sql =
      db.mode === "POSTGRES"
        ? "SELECT id, slug, status FROM salons WHERE slug = $1"
        : "SELECT id, slug, status FROM salons WHERE slug = ?";

    const salon = await db.get(sql, [req.params.slug]);

    if (!salon) return res.status(404).json({ error: "SALON_NOT_FOUND" });
    if (salon.status !== "active")
      return res.status(403).json({ error: "SALON_INACTIVE" });

    req.salon = salon;
    req.salon_id = salon.id;
    next();
  } catch (e) {
    console.error("[SALON RESOLVER ERROR]", e);
    res.status(500).json({ error: "SALON_RESOLVE_FAILED" });
  }
});

// ===== RESOLVE API =====
app.get("/s/:slug/resolve", (req, res) => {
  res.json({ ok: true, salon_id: String(req.salon_id), slug: req.salon.slug });
});

// ===== START =====
bootstrap().then(() => {
  app.listen(PORT, () => {
    console.log(`TOTEM API running on port ${PORT}`);
  });
});
