-- TOTEM migration
-- Purpose: link salons ↔ masters ↔ services with contextual price/duration
-- Date: 2026-02-01
-- Safe: additive only (no changes to existing tables)

BEGIN;

CREATE TABLE IF NOT EXISTS public.salon_master_services (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  salon_id     integer NOT NULL,
  master_id    integer NOT NULL,
  service_pk   integer NOT NULL,

  price        integer NOT NULL CHECK (price >= 0),
  duration_min integer NOT NULL CHECK (duration_min > 0),
  active       boolean NOT NULL DEFAULT true,

  created_at   timestamp without time zone NOT NULL DEFAULT now(),

  CONSTRAINT fk_sms_salon
    FOREIGN KEY (salon_id) REFERENCES public.salons(id) ON DELETE CASCADE,

  CONSTRAINT fk_sms_master
    FOREIGN KEY (master_id) REFERENCES public.masters(id) ON DELETE CASCADE,

  CONSTRAINT fk_sms_service
    FOREIGN KEY (service_pk) REFERENCES public.services(id) ON DELETE CASCADE,

  CONSTRAINT uq_sms_unique
    UNIQUE (salon_id, master_id, service_pk)
);

-- Helpful indexes for read paths
CREATE INDEX IF NOT EXISTS idx_sms_salon_active
  ON public.salon_master_services (salon_id, active);

CREATE INDEX IF NOT EXISTS idx_sms_master_active
  ON public.salon_master_services (master_id, active);

CREATE INDEX IF NOT EXISTS idx_sms_service
  ON public.salon_master_services (service_pk);

COMMIT;
