-- ============================================================
-- TOTEM — Financial Core Schema v1 (CANONICAL)
-- Target: PostgreSQL + local fallback via better-sqlite3 (SQLite)
--
-- Rules:
-- - IDs are TEXT (generated by app) to stay cross-db.
-- - Ledger is designed append-only by contract (no UPDATE paths).
-- - FK + indexes + currency-aware numeric fields.
-- ============================================================

-- ----------------------------
-- Common helpers (portable)
-- ----------------------------
-- NOTE: Keep types portable: TEXT, INTEGER, NUMERIC, TIMESTAMP
-- NOTE: JSON stored as TEXT (provider payloads)

-- ============================================================
-- 1) DOMAIN TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS client (
  id                TEXT PRIMARY KEY,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status            TEXT NOT NULL DEFAULT 'active',  -- active|blocked|deleted
  name              TEXT,
  phone             TEXT,
  email             TEXT,

  external_ref      TEXT,   -- Odoo/CRM id, etc.
  meta_json         TEXT
);

CREATE INDEX IF NOT EXISTS idx_client_status ON client(status);
CREATE INDEX IF NOT EXISTS idx_client_phone  ON client(phone);
CREATE INDEX IF NOT EXISTS idx_client_email  ON client(email);

CREATE TABLE IF NOT EXISTS salon (
  id                TEXT PRIMARY KEY,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status            TEXT NOT NULL DEFAULT 'active',  -- active|blocked|deleted
  slug              TEXT,
  title             TEXT,
  phone             TEXT,
  email             TEXT,
  address           TEXT,

  owner_client_id   TEXT,   -- optional
  external_ref      TEXT,
  meta_json         TEXT,

  FOREIGN KEY (owner_client_id) REFERENCES client(id)
);

CREATE INDEX IF NOT EXISTS idx_salon_status ON salon(status);
CREATE INDEX IF NOT EXISTS idx_salon_slug   ON salon(slug);
CREATE INDEX IF NOT EXISTS idx_salon_owner  ON salon(owner_client_id);

CREATE TABLE IF NOT EXISTS master (
  id                TEXT PRIMARY KEY,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status            TEXT NOT NULL DEFAULT 'active',  -- active|blocked|deleted
  salon_id          TEXT,
  display_name      TEXT,
  phone             TEXT,
  email             TEXT,

  external_ref      TEXT,
  meta_json         TEXT,

  FOREIGN KEY (salon_id) REFERENCES salon(id)
);

CREATE INDEX IF NOT EXISTS idx_master_status  ON master(status);
CREATE INDEX IF NOT EXISTS idx_master_salon   ON master(salon_id);
CREATE INDEX IF NOT EXISTS idx_master_phone   ON master(phone);
CREATE INDEX IF NOT EXISTS idx_master_email   ON master(email);

-- ============================================================
-- 2) WALLET & LEDGER CORE
-- ============================================================

-- Wallet is per owner + currency
-- owner_type: 'MASTER' | 'SALON' | 'PLATFORM' | 'CLIENT'
CREATE TABLE IF NOT EXISTS wallet (
  id                TEXT PRIMARY KEY,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  owner_type        TEXT NOT NULL,
  owner_id          TEXT NOT NULL,
  currency          TEXT NOT NULL DEFAULT 'USD',

  status            TEXT NOT NULL DEFAULT 'active',  -- active|blocked
  label             TEXT,

  -- optional references (denormalized convenience)
  salon_id          TEXT,
  master_id         TEXT,
  client_id         TEXT,

  meta_json         TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_wallet_owner_currency
  ON wallet(owner_type, owner_id, currency);

CREATE INDEX IF NOT EXISTS idx_wallet_owner ON wallet(owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_wallet_currency ON wallet(currency);
CREATE INDEX IF NOT EXISTS idx_wallet_status ON wallet(status);

-- Ledger entries represent movements and reserves.
-- Direction model:
-- - from_wallet_id nullable
-- - to_wallet_id nullable
-- entry_kind examples:
-- - CREDIT, DEBIT, TRANSFER, RESERVE, RELEASE, FEE, REVERSAL, ADJUSTMENT
-- balance is computed by summing entries; do not store balances here.
CREATE TABLE IF NOT EXISTS ledger_entry (
  id                 TEXT PRIMARY KEY,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  currency           TEXT NOT NULL DEFAULT 'USD',
  amount             NUMERIC NOT NULL,                 -- positive amount
  entry_kind         TEXT NOT NULL,                    -- see above

  from_wallet_id     TEXT,
  to_wallet_id       TEXT,

  -- reservation / availability support
  is_reserved        INTEGER NOT NULL DEFAULT 0,        -- 0/1
  reserved_group_id  TEXT,                             -- payout/payment hold group

  -- business context
  context_type       TEXT NOT NULL,                    -- BOOKING|PAYMENT|PAYOUT|INVOICE|ADJUSTMENT|...
  context_id         TEXT NOT NULL,

  -- idempotency (critical)
  idempotency_key    TEXT NOT NULL,

  -- attribution / audit
  rule_code          TEXT,                             -- fee_rule.code when fee applied
  note               TEXT,
  meta_json          TEXT,

  FOREIGN KEY (from_wallet_id) REFERENCES wallet(id),
  FOREIGN KEY (to_wallet_id)   REFERENCES wallet(id)
);

-- Prevent duplicates (idempotency)
CREATE UNIQUE INDEX IF NOT EXISTS ux_ledger_idempotency
  ON ledger_entry(idempotency_key);

-- Fast lookups
CREATE INDEX IF NOT EXISTS idx_ledger_created_at
  ON ledger_entry(created_at);

CREATE INDEX IF NOT EXISTS idx_ledger_context
  ON ledger_entry(context_type, context_id);

CREATE INDEX IF NOT EXISTS idx_ledger_from_wallet
  ON ledger_entry(from_wallet_id);

CREATE INDEX IF NOT EXISTS idx_ledger_to_wallet
  ON ledger_entry(to_wallet_id);

CREATE INDEX IF NOT EXISTS idx_ledger_reserved_group
  ON ledger_entry(reserved_group_id);

CREATE INDEX IF NOT EXISTS idx_ledger_kind
  ON ledger_entry(entry_kind);

-- ============================================================
-- 3) PAYMENTS (BUSINESS FACT) + PROVIDER TX (TECH FACT)
-- ============================================================

CREATE TABLE IF NOT EXISTS payment_provider (
  id                TEXT PRIMARY KEY,
  created_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  code              TEXT NOT NULL,          -- FREEDOMPAY|STRIPE|... (future)
  display_name      TEXT,
  status            TEXT NOT NULL DEFAULT 'disabled',  -- disabled|enabled

  -- config stored as json text (secrets are in env; store only non-sensitive)
  config_json       TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_provider_code
  ON payment_provider(code);

CREATE INDEX IF NOT EXISTS idx_payment_provider_status
  ON payment_provider(status);

-- payment = business truth
CREATE TABLE IF NOT EXISTS payment (
  id                 TEXT PRIMARY KEY,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status             TEXT NOT NULL DEFAULT 'pending',  -- pending|confirmed|failed|canceled
  currency           TEXT NOT NULL DEFAULT 'USD',
  amount             NUMERIC NOT NULL,

  -- who pays / who receives (business)
  payer_type         TEXT,         -- CLIENT|...
  payer_id           TEXT,
  payee_wallet_id    TEXT,         -- wallet receiving after confirmation

  -- context
  context_type       TEXT NOT NULL, -- BOOKING|WALLET_TOPUP|SERVICE_INVOICE
  context_id         TEXT NOT NULL,

  -- provider link
  provider_code      TEXT,          -- e.g. FREEDOMPAY
  provider_id        TEXT,          -- payment_provider.id
  provider_hint      TEXT,          -- optional

  -- safety
  idempotency_key    TEXT NOT NULL,

  meta_json          TEXT,

  FOREIGN KEY (provider_id)     REFERENCES payment_provider(id),
  FOREIGN KEY (payee_wallet_id) REFERENCES wallet(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_payment_idempotency
  ON payment(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_payment_status
  ON payment(status);

CREATE INDEX IF NOT EXISTS idx_payment_context
  ON payment(context_type, context_id);

CREATE INDEX IF NOT EXISTS idx_payment_provider
  ON payment(provider_id);

-- provider_tx = technical transaction (webhook / redirect / provider ids)
CREATE TABLE IF NOT EXISTS payment_provider_tx (
  id                   TEXT PRIMARY KEY,
  created_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  provider_code         TEXT NOT NULL,           -- FREEDOMPAY|...
  provider_payment_id   TEXT,                    -- provider's payment/transaction id
  status                TEXT NOT NULL,           -- created|processing|succeeded|failed|canceled

  payment_id            TEXT NOT NULL,           -- business payment
  currency              TEXT NOT NULL DEFAULT 'USD',
  amount                NUMERIC NOT NULL,

  -- idempotency / dedupe
  provider_event_id     TEXT,                    -- webhook event id
  idempotency_key       TEXT NOT NULL,

  raw_json              TEXT,                    -- webhook payload / provider response
  meta_json             TEXT,

  FOREIGN KEY (payment_id) REFERENCES payment(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_provider_tx_idempotency
  ON payment_provider_tx(idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_provider_tx_provider_payment_id
  ON payment_provider_tx(provider_code, provider_payment_id);

CREATE INDEX IF NOT EXISTS idx_provider_tx_payment
  ON payment_provider_tx(payment_id);

CREATE INDEX IF NOT EXISTS idx_provider_tx_status
  ON payment_provider_tx(status);

-- ============================================================
-- 4) FEE ENGINE (CONFIG, NOT CODE)
-- ============================================================

CREATE TABLE IF NOT EXISTS fee_rule (
  id                 TEXT PRIMARY KEY,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  code               TEXT NOT NULL,               -- PLATFORM_FEE|PROVIDER_FEE|...
  status             TEXT NOT NULL DEFAULT 'enabled', -- enabled|disabled

  -- scope filters
  applies_to         TEXT NOT NULL,               -- PAYMENT|PAYOUT
  context_type       TEXT,                        -- optional filter: BOOKING|...
  currency           TEXT,                        -- optional filter

  -- calculation
  mode               TEXT NOT NULL,               -- percent|fixed|hybrid
  percent_value      NUMERIC,                     -- 0..100
  fixed_value        NUMERIC,                     -- absolute amount
  min_value          NUMERIC,
  max_value          NUMERIC,

  -- routing (where fee goes)
  fee_wallet_id      TEXT,                        -- platform wallet, etc.

  priority           INTEGER NOT NULL DEFAULT 100, -- lower = earlier
  note               TEXT,
  meta_json          TEXT,

  FOREIGN KEY (fee_wallet_id) REFERENCES wallet(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_fee_rule_code
  ON fee_rule(code);

CREATE INDEX IF NOT EXISTS idx_fee_rule_status
  ON fee_rule(status);

CREATE INDEX IF NOT EXISTS idx_fee_rule_applies
  ON fee_rule(applies_to);

CREATE INDEX IF NOT EXISTS idx_fee_rule_priority
  ON fee_rule(priority);

-- ============================================================
-- 5) PAYOUT (SAFE EXIT)
-- ============================================================

CREATE TABLE IF NOT EXISTS payout (
  id                 TEXT PRIMARY KEY,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status             TEXT NOT NULL DEFAULT 'requested', -- requested|processing|completed|failed|canceled
  currency           TEXT NOT NULL DEFAULT 'USD',
  amount             NUMERIC NOT NULL,

  owner_type         TEXT NOT NULL,         -- MASTER|SALON|PLATFORM
  owner_id           TEXT NOT NULL,
  from_wallet_id     TEXT NOT NULL,         -- wallet to reserve/debit from

  -- reservation group used in ledger_entry.reserved_group_id
  reserve_group_id   TEXT NOT NULL,

  -- provider linkage (future)
  provider_code      TEXT,
  provider_payout_id TEXT,
  raw_json           TEXT,

  -- idempotency
  idempotency_key    TEXT NOT NULL,

  note               TEXT,
  meta_json          TEXT,

  FOREIGN KEY (from_wallet_id) REFERENCES wallet(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_payout_idempotency
  ON payout(idempotency_key);

CREATE INDEX IF NOT EXISTS idx_payout_status
  ON payout(status);

CREATE INDEX IF NOT EXISTS idx_payout_owner
  ON payout(owner_type, owner_id);

CREATE INDEX IF NOT EXISTS idx_payout_wallet
  ON payout(from_wallet_id);

-- ============================================================
-- 6) SERVICE INVOICE (PLATFORM MONETIZATION)
-- ============================================================

CREATE TABLE IF NOT EXISTS service_invoice (
  id                 TEXT PRIMARY KEY,
  created_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  status             TEXT NOT NULL DEFAULT 'pending', -- pending|paid|overdue|canceled
  currency           TEXT NOT NULL DEFAULT 'USD',
  amount             NUMERIC NOT NULL,

  -- who owes the platform
  owner_type         TEXT NOT NULL,        -- SALON|MASTER
  owner_id           TEXT NOT NULL,
  owner_wallet_id    TEXT,                 -- payer wallet
  platform_wallet_id TEXT,                 -- receiver wallet

  -- period info
  period_key         TEXT NOT NULL,        -- e.g. 2026-02
  due_at             TIMESTAMP,

  -- payment link (business)
  payment_id         TEXT,

  idempotency_key    TEXT NOT NULL,

  note               TEXT,
  meta_json          TEXT,

  FOREIGN KEY (owner_wallet_id)    REFERENCES wallet(id),
  FOREIGN KEY (platform_wallet_id) REFERENCES wallet(id),
  FOREIGN KEY (payment_id)         REFERENCES payment(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_invoice_idempotency
  ON service_invoice(idempotency_key);

CREATE UNIQUE INDEX IF NOT EXISTS ux_invoice_owner_period
  ON service_invoice(owner_type, owner_id, period_key);

CREATE INDEX IF NOT EXISTS idx_invoice_status
  ON service_invoice(status);

CREATE INDEX IF NOT EXISTS idx_invoice_due_at
  ON service_invoice(due_at);

-- ============================================================
-- 7) REPORTING HELPERS (optional views via code; keep schema portable)
-- ============================================================
-- NOTE: Views are intentionally omitted here for cross-db portability.
-- Implement balance computations in services via SUM(ledger_entry...) queries.
-- ============================================================

-- END OF FILE
